main: com.warhut.banmanager.BanManager
name: BanManager
version: 1.0
description: MySQL Based ban manager plugin.
commands:
   tempban:
     description: temporary ban a player.
   ban:
     description: permanently ban a player.
   banlist:
     description: get the banlist.
   filltable:
     description: fill table.
   pardon:
     description: unban a player.
   ipban:
     description: ip ban a player
   ip:
     description: check the ip of a player
    